#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export DOTNET_REFERENCE_ASSEMBLIES_PATH=$(dirname `which mono`)/../lib/mono/xbuild-frameworks
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
exec mono "$DIR/dotnet.exe" "$@"
